### ISSUE TITLE
Fatal error when Symbiote\QueuedJobs is not installed

### ISSUE THREAD

**Issue by Dynamo6Dev** [signify-nz/silverstripe-security-headers#11]
Running silverstripe/framework 4.12.3

**Steps to reproduce:**
Install signify-nz/silverstripe-security-headers @ version 2.1.1
Run dev/build?flush=1

**Output:**
Fatal error: Uncaught Error: Class "Symbiote\QueuedJobs\Services\AbstractQueuedJob" not found in C:\Users\Mike\Documents\wwwroot\project-name\silverstripe\vendor\signify-nz\silverstripe-security-headers\src\Jobs\RemoveOldCSPViolationsJob.php on line 14

**Comment by sig-steve** [comment]
I've added an explicit dependency on `symbiote/silverstripe-queuedjobs` (^4.8) and have released version 2.1.2.

**Comment by sig-steve** [comment]
No further comments for two months - I'll closing this issue.
