### ISSUE TITLE
The report-uri directive has been deprecated in favour of report-to directive

### ISSUE THREAD

**Issue by axllent** [signify-nz/silverstripe-security-headers#12]
Tools such as the OWASP ZAP scanner are reporting the Content-Security-Policy header [report-uri](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri) has been deprecated, and replaced by [report-to](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to). It's not just a simple rewording, but rather a few extra steps to define a group, and then reference to that group. Please see the above links for more information.

**Comment by sig-steve** [comment]
Have you tried the existing [report-to](https://github.com/signify-nz/silverstripe-security-headers/blob/master/docs/en/02_csp-options.md#enabling-report-to) functionality? I don't want to set your expectations too high as I'm not sure we've ever used it, and I was quite surprised when I saw it in the documentation.

It looks like the API behind report-to has since moved on from what was implemented: the Reporting API v1 is saying to use a Reporting-Endpoints header rather than a Report-To header.

**Comment by axllent** [comment]
Thanks @sig-steve - I have obviously completely overlooked that, my apologies! I'll investigate and report back some time next week hopefully!

**Comment by sig-steve** [comment]
All good. I only discovered it when looking into what we might need to do to support it!

**Comment by axllent** [comment]
Hi @sig-steve. I have had a bit of time to look into this now. I can confirm that adding `use_report_to: true` does add the new headers, however Chrome then does not report anything at all. Firefox continues to work, but that would be because it doesn't support `report-to` (yet) so falls back to the former.

I'm not sure if this has to do with `Reporting-Endpoints` vs: `Report-To` (I think they are both valid). I did notice that the examples do not escape slashes in the URL, whereas json_encode (by default does) - but adding ` JSON_UNESCAPED_SLASHES` to the `return json_encode($header, JSON_UNESCAPED_SLASHES);` did not that - but it did not. I then changed `Report-To` to `reporting-endpoints: signify-csp-violation="<url>"`  but that didn't fix it either (for Chrome) - so I'm out of ideas here. I'm probably missing something obvious here, however I can conclude (at this point) that adding the [report-to](https://github.com/signify-nz/silverstripe-security-headers/blob/master/docs/en/02_csp-options.md#enabling-report-to) functionality breaks reporting altogether for browsers supporting report-to, so this is an issue. Hopefully your experience with this can shed some light on the matter.

**Comment by axllent** [comment]
Oh actually - reading the first point on https://www.w3.org/TR/reporting/#process-header
> 1. Abort these steps if response’s [HTTPS state](https://fetch.spec.whatwg.org/#concept-response-https-state) is not "modern", and the [origin](https://url.spec.whatwg.org/#concept-url-origin) of response’s [url](https://fetch.spec.whatwg.org/#concept-response-url) is not [potentially trustworthy](https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy).

I _guess_ that's their way of saying the report URI must be HTTPS (which my dev environment isn't)? Sorry, just throwing out thoughts at the moment... trying to help.

**Comment by sig-steve** [comment]
For what it's worth, I've tried out the `use_report_to` option, and it appears to perform as expected - over HTTPS.
