### ISSUE TITLE
Silverstripe 5 support

### ISSUE THREAD

**Issue by Sitetools** [signify-nz/silverstripe-security-headers#13]
Could you please let me know if or when you'll offer Silverstripe 5 support?
We use your addon on a few of our key projects and would like to continue using it.
Also do you have a timeline for when you'll support PHP 8.2.

@axllent

**Comment by sig-critchie** [comment]
Hi, @Sitetools I will raise this at our next developer meeting and update this ticket once I konw more.

Cheers,
Charles

**Comment by axllent** [comment]
Thanks @sig-critchie. Can you provide some indication as to when that next developer meeting is scheduled? We're just trying to plan some upgrades and need to know the timeline/support status of modules like this. Thanks.

**Comment by sig-critchie** [comment]
Hi @axllent we have discussed this internally and unfortunately, we cannot give a definite timeline. The module will be updated as part of client site upgrades. This is likely to be sometime in the next year, but we cannot guarantee this.

We are happy to accept a PR should you create one.

**Comment by axllent** [comment]
Thanks @sig-critchie for the response. We definitely cannot wait until next year, so I'll see what we can sort out re: a PR :+1:

**Comment by axllent** [comment]
We have just tested your module successfully on Silverstripe 5. Other than minor changes within the `composer.json` file to expand the version restraints to include both Silverstripe 4 and 5, no other code changes are necessary (works out of the box). I have provided a PR for you via #14

**Comment by sig-steve** [comment]
Hi @axllent, thank you for doing this. I'll try to get it merged this weekend.

**Comment by sig-steve** [comment]
Thanks @axllent, I've just released your pull request as 2.1.3.

**Comment by axllent** [comment]
Thanks mate, appreciated 👍

**Comment by Sitetools** [comment]
Excellent - thank you!
